sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
env:
  global:
  - secure: VSPGykZQaXIebSEijc06VXLUX/L2OGveEvhMp13CyPl9i65z9DZ0FlFXt3xRRitGjXIYgIj14TTYSd3SSKCeNVW//ZkqRwmC8AqnvF0DAeEvmVCqFe45Kn1IpspQ7SED/wzfLWXjpnCOLyHSMvgLwq8WSwyIcpHoYbyCC0XNq/A4ljepCJpDjIzTHJNR+PgvT7PObLhJ2LKb4BS95g37WNWzMo9+i8/r6dUdcMFQMOEmBwwg2GuA66MbuKwMYZoMFojfaFNHMnBQqJgUqIdtL2NKlMlAoSQVTrXGbyJ+3S1Vres4jvGAiWcTwWyLTj9Cu5hqYBB3Hot3zUM+h+YXJjhcQtDbfKQ6TU4LTFcP5Pii0sen2KAd+Q3pHxdJJE4piakKTeNxfRSUny6TicD2CPtWfFOTZQX2N5VgVmwuopKp4eu6Pj3Y9BLKccNsGukbi+5lQHrPD4yV5oChfU/xXal1fpz5BZ2nvGxQHpUmE6nSo99CrcYMDzLPAPPcUB2t4N+1RzKs0M/2VgDPlywH5UJxGYk79Po2sz1V4hN30OYZAiZvIeDwA5epdrfcL3AcFjwsnoOi7SHLkj3Kk4z2WKcO2AMV8y0aoLBqvnyYejHSgiwq0n+SjAr6LfwLtzHuAaNFmABHeyOTsaiKVpQA3ghr8e+rENsQFiAcOpCYTY8=
